### ISSUE TITLE
I think you might have intended to use the glnoerror constant, line 74, worldwindow.cpp

### ISSUE THREAD

**Issue by JonathanFerron** [benbotto/rubiks-cube-cracker#1]
https://github.com/benbotto/rubiks-cube-cracker/blob/1622d3622e6abf2d366b7e12bde9763ca6a86515/OpenGLSeed/View/WorldWindow.cpp#L74

**Comment by benbotto** [comment]
Thanks for looking into this.  That check for `GL_INVALID_ENUM` is actually intentional.  GLEW 1.10.0 is used in this project, which was the latest version when I wrote this code.  Take a look here: [https://www.khronos.org/opengl/wiki/OpenGL_Loading_Library#Initialization_of_GLEW_1.13.0_and_earlier](https://www.khronos.org/opengl/wiki/OpenGL_Loading_Library#Initialization_of_GLEW_1.13.0_and_earlier)

> You might still get GL_INVALID_ENUM (depending on the version of GLEW you use)

Feel free to reopen if you think I've closed this issue in error.
